services:
  backend:
    build: .

    container_name: ott_backend

    ports:
      - "5000:5000"

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - postgres

    environment:
      PORT: 5000

      DATABASE_URL: postgresql://postgres:password@postgres:5432/ott_db

      JWT_SECRET: your_jwt_secret

      CLOUDINARY_CLOUD_NAME: your_cloud_name
      CLOUDINARY_API_KEY: your_api_key
      CLOUDINARY_API_SECRET: your_api_secret

    restart: always

  postgres:
    image: postgres:16-alpine

    container_name: ott_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bansi.,&1510
      POSTGRES_DB: movix

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: